@startuml diagram
!theme plain
' left to right direction

skinparam interface {
  BackgroundColor LightGreen
}

skinparam note {
  BackgroundColor Yellow
}

package "Контракты" as Contracts {
  interface "IConsumer" as IConsumer
  interface "IPublisher" as IPublisher
}

component "Брокер (gRPC сервис)" as Broker {
  component "Компонент\nпринимающий запросы" as RequestReceiver #LightYellow
  portin "Приём IPublisher" as pIn #lightgreen

  component "Обработчик очередей" as QueueHandler #LightYellow

  package "Сборщик аналитики" as Analytics {
    component "API для администрирования" as AdminAPI
  }

  component "Маршрутизатор" as Router #LightYellow
  portout "Отправка IConsumer" as pOut #lightgreen

  component "Конфигуратор" as Config #LightYellow
  note bottom of Config
    Светло жёлтым
    помечены конфигурируемые
    элементы
  end note

  database "MessageStorage" #lightblue {
    component "Dead Letter Queue" as DLQ
    component "Хранилище сообщений" as IMessageStorage
  }

  RequestReceiver --> QueueHandler : передача сообщений в очередь
  QueueHandler --> Router : маршрутизация сообщений

  QueueHandler --> Analytics : сбор метрик
  QueueHandler --> DLQ : сохранение мёртвых сообщений
  QueueHandler --> IMessageStorage

  RequestReceiver <-- pIn : ожидает сообщения
  pIn <-- IPublisher : ожидает сообщения

  Router --> pOut : предоставляет сообщения
  pOut --> IConsumer : предоставляет сообщения
}

package "Broker.Client" as Library
Library -- Contracts : предоставляет готовые удобные методы для IConsumer и IProducer\n а также инструменты для конфигурации подключения


note bottom of Library
  Библиотека в NuGet
  для работы с сервисом
end note

node "ProducerClient" as Producer #red
node "ConsumerClient" as Consumer #red
Producer --> Library : использует
Consumer --> Library : использует

node "Admin UI" as AdminUI
AdminUI --> AdminAPI : использует

interface IBrokerManager
IBrokerManager --> Config : управляет

@enduml