GET http://localhost:5256/api/metrics/queueNameHere
Accept: application/json
###
GET http://localhost:5256/api/status
Accept: application/json
###
GET http://localhost:5256/api/config
Accept: application/json
###
GET http://localhost:5256/api/list-queues
Accept: application/json